name: Lint Code Base

on:
  push:
    branches:
      - master
      - 'release/**'
      - develop
  pull_request:
    branches:
      - master
      - 'release/**'
      - develop

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}